### ISSUE TITLE
404 Typekit source

### ISSUE THREAD

**Issue by pamo** [radicalbarracuda/sf-feminist-book-club#4]
![image](https://cloud.githubusercontent.com/assets/784889/24834140/c410045e-1c91-11e7-9f5b-3e7ab8ddaaea.png)

[https://use.typekit.net/pti6qle.js](https://use.typekit.net/pti6qle.js)

**Comment by lizgene** [comment]
Totally - I didn't add the `radicalbarracuda` heroku URL to our Typekit kit. Added, error resolved 👍
